import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './component/nav'

import { config } from '@fortawesome/fontawesome-svg-core'
import "@fortawesome/fontawesome-svg-core/styles.css"
config.autoAddCss = false ;
// 전역으로 쓸수 있게 전역 레이아웃에 import 시켜주는것이다.




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // 전역으로 컴포넌트를 하고싶을땐 layout.tsx
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <Nav />
        <p>글로벌 레이아웃</p>
        {children}
        </body>
    </html>
  )
}
